//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Million.Book.Modelo.EntityModel
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class Libro
    {
        [Key, Column(Order = 0)]
        [ForeignKey("idLibro")]
        public long idLibro { get; set; }
        public int isbn { get; set; }
        public long idEditorial { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string numeroPagina { get; set; }
    }
}
