//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Million.Book.Modelo.EntityModel
{
	using Microsoft.EntityFrameworkCore;
	using System;
    using System.Data.Entity.Infrastructure;
    
    public partial class MillionEntities : DbContext
    {
        public MillionEntities(DbContextOptions<MillionEntities> options) : base(options)
        {
        }

        public virtual DbSet<Editorial> Editorial { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<ExceptionControl> ExceptionControl { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}
